@host = {{FIREBLOCKS_URL}}/v1
@asset = {{ASSET}}

###
# @name accounts
GET /vault/accounts_paged?assetId={{asset}}&minAmountThreshold={{THRESHOLD}}

###
# @ref accounts
GET /vault/accounts/{{accounts.accounts[0].id}}/{{asset}}

###
# @ref accounts
GET /vault/accounts/{{accounts.accounts[0].id}}/{{asset}}/addresses

###
# @name transaction
# @ref accounts
POST /transactions

{
    "assetId" : "{{asset}}",
    "amount" : {{AMOUNT}},
    "source" : {
        "type" : "VAULT_ACCOUNT",
        "id" : "{{accounts.accounts[0].id}}"
    },
    "destination" : {
        "type" : "ONE_TIME_ADDRESS",
        "oneTimeAddress" : {
            "address" : "{{EXTERNALRECEIVER}}"
        }
    }
}

###
# @ref transaction
GET /transactions/{{transaction.id}}

###
# @name secondAccountAddresses
GET /vault/accounts/{{accounts.accounts[1].id}}/{{asset}}/addresses

###
# @name transactionToSecond
# @ref secondAccountAddresses
# @ref accounts
POST /transactions

{
    "assetId" : "{{asset}}",
    "amount" : {{AMOUNT}},
    "source" : {
        "type" : "VAULT_ACCOUNT",
        "id" : "{{accounts.accounts[0].id}}"
    },
    "destination" : {
        "type" : "ONE_TIME_ADDRESS",
        "oneTimeAddress" : {
            "address" : "{{secondAccountAddresses[0].address}}"
        }
    }
}

###
# @ref transactionToSecond
GET /transactions/{{transactionToSecond.id}}

###
POST /vault/accounts

{
    "name" : "{{$guid}}"
}