on:
  push:
    paths:
      - '.github/workflows/nuget.yml'
      - 'lib/**'
  workflow_dispatch:
    
jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: lib/Fire.Client
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}